# Generated by Django 3.2 on 2021-04-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('assigned', models.CharField(max_length=100)),
                ('trackers', models.CharField(max_length=500)),
                ('status', models.SmallIntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Testing'), (4, 'Done')], default=1)),
                ('started', models.DateField(blank=True, null=True)),
                ('completed', models.DateField(blank=True, null=True)),
                ('planned_due_time', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
